In [1]:
import pandas as pd
df_train=pd.read_csv("train.csv")
df_test=pd.read_csv("test_f.csv")

In [2]:
# Separate features and target
X_train = df_train.drop(columns=["label"])
y_train = df_train["label"]
# Separate features and target
X_test = df_test.drop(columns=["label"])
y_test = df_test["label"]

In [3]:
from sklearn.ensemble import ExtraTreesClassifier
import numpy as np

In [4]:
import joblib

In [5]:
best_et_BOGP=joblib.load("best_et_BOGP.pkl")

In [6]:
clf_et=ExtraTreesClassifier(**best_et_BOGP,random_state=42)

In [7]:
clf_et.fit(X_train,y_train)

ExtraTreesClassifier(max_depth=60, random_state=42)

In [8]:
y_pred = clf_et.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score

In [10]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7118933763515201


In [11]:
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report


In [12]:
# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
balanced_acc = balanced_accuracy_score(y_test, y_pred)
f1_macro = f1_score(y_test, y_pred, average='macro')
f1_weighted = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [13]:
print(f"Accuracy: {accuracy:.4f}")
print(f"Balanced Accuracy: {balanced_acc:.4f}")
print(f"F1 Score (Macro): {f1_macro:.4f}")
print(f"F1 Score (Weighted): {f1_weighted:.4f}")
print(f"Precision (Weighted): {precision:.4f}")
print(f"Recall (Weighted): {recall:.4f}")
print("\nConfusion Matrix:\n", cm)
print("\nClassification Report:\n", report)

Accuracy: 0.7119
Balanced Accuracy: 0.5997
F1 Score (Macro): 0.5091
F1 Score (Weighted): 0.7586
Precision (Weighted): 0.8579
Recall (Weighted): 0.7119

Confusion Matrix:
 [[23067  1405    13   184   456  7980    15   156   349     7]
 [    2     4     3     6    56    17     1     8     3     0]
 [    2     8    32     4    11    26     0    13     9     0]
 [    5    19    24   600   421    73    23    52    50     4]
 [   39    60    52   445  5814   199    38   318   187    16]
 [  418    15    27    60   280  2949    18    90   433     4]
 [    6     3    13    94   250    41  2421    20    17     5]
 [    3    11    29    26   139    31     3  1889    77     1]
 [    2     1     8    27    21    33     0    14   267     5]
 [    0     0     0     0    14     2     1     0     1    26]]

Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.69      0.81     33632
           1       0.00      0.04      0.00       100
          

In [14]:
et1=clf_et

In [15]:
joblib.dump(et1, "et1.pkl")

['et1.pkl']